### ISSUE TITLE
testing package included in downstream clients

### ISSUE THREAD

**Issue by kruskall** [elastic/opentelemetry-lib#32]
The `testing.go` file imports the `testing` package but it's non-test file in a non-testing package. 

https://github.com/elastic/opentelemetry-lib/blob/3df0d4f515c90726a090666556ed38cf2aa0cdd8/remappers/internal/testing.go#L21

This causes downstream clients to include the testing package in the final binary.

(This is a side effect of some of the downstream clients having DCE disabled due to problematic dependencies)

**Comment by lahsivjar** [comment]
https://github.com/elastic/opentelemetry-lib/pull/23/files PR should fix it. @gizas Can we get that ready to merge?
