### ISSUE TITLE
[enrichments] Add exception based enrichment for span events

### ISSUE THREAD

**Issue by lahsivjar** [elastic/opentelemetry-lib#86]
Span events should be enriched with the following attributes:

- `error.id` (unique number for the given error instance)
- `error.exception.message`
- `error.exception.stacktrace`
- `error.exception.cause`
- `error.exception.handled`
- `error.grouping_key`

Also, add the following as enrichments for error events:
- `transaction.type`
- `transaction.sampled`

**Comment by AlexanderWert** [comment]
@lahsivjar FYI: added `error.id` to the above list!

**Comment by lahsivjar** [comment]
This is done! Closing!
